[options]
addons_path = /usr/lib/python3/dist-packages/odoo/addons,/mnt/extra-addons,/mnt/custom_addons
data_dir = /var/lib/odoo
admin_passwd = admin

db_host = odoo-dev-db-1
db_port = 5432
db_user = odoo
db_password = odoo
db_name = first_odoo

